using System.Collections;
using System.Collections.Generic;
using UnityEngine;

public class RandomPhrase : MonoBehaviour
{
    List<string> frases = new List<string>{
        "No consigues la vida que sueñas si te la dan, la consigues si naces rico, y no es tu caso.",
        "Ya no hay días buenos, solo días.",
        "Memento Mori.",
        "A veces se gana, a veces se pierde, pero total, te vas a morir.",
        "¿Tienes miedo?\n\nYo tambien.",
        "Algún día nadie recordará tu nombre.",
        "Tu existencia será borrada algún día por el inexorable paso del tiempo.",
        "¿Aún sigues aquí?\n\nPatético.",
        "El sol explotará algún día.",
        "Todo es culpa tuya por no nacer en una época donde comprar casa eran dos euros.",
        "Recuerda que a final de mes hay que pagar deudas.",
        "Si crees que puedes lograr algo, para antes de hacerte daño.",
        "Mejor llorar que reir",
        "Hueles mal, duchate antes de dejarte más en ridiculo.",
        "Cree en el fracaso, bañate en él",
        "Hoy no me apetece decirte nada.",
        "Mejor deja para mañana lo que no quieras hacer\n\nTal vez con suerte te mueres y no tienes que hacerlo.",
        "Cuando mueres no te vas a un mundo de fantasía, imbecil.",
        "Otro día, otro euro.",
        "¿Sabías que incluso usando cinturón de seguridad, la gente muere en accidentes de coche?\n\nMe pareció un dato interesante.",
        "No hay segundas oportunidad, solo autoconvencerte de que tus fracasos no lo son.",
        "Lo único que no debes perder en esta vida es la esperanza de que algún día morirás.",
        "Puede parecer que otras personas lo tienen más fácil que tú.\n\nVengo a confirmarte que es así.",
        "Todo es posible si naces rico, salvo no morirte.",
        "No puedes controlar lo que te pasa pero puedes pegarte un tiro.",
        "Piensa que al menos no eres americano.",
        "Yo creo que Oppenheimer no tenía razón, una buena bomba termonuclear en Israel ahora mismo estaría bien.",
        "Siempre ten presente que:\n\n'Aquel que cojea, fue por no mirar antes de cruzar'.",
        "Alegraté, al menos no eres un puto incel, ¿verdad?",
        "Un día serás tan viejo que tendrás que elegir entre no follar o altas posibilidades de sufrir un infarto.",
        "Tienes un  50% de posibilidades de morirte de algo cerebral o cardiovascular, asique ten miedo.",
        "Tienes razón, algo esta mal con este mundo, y ni tu ni nadie va a poder arreglarlo.",
        "Al menos no eres el pringao que escribió todas mis frases pero aún así te vas a morir algún día.",
        "No puedes volver al pasado, solo lamentarte de haberla cagado.",
        "Tienes enemigos.\n\nEsperan tu caida.",
        "Lo ganadores no esperan oportunidades, las compran.",
        "En caso de que nadie te lo haya dicho hoy:\n\nlavate los dientes.",
        "La mejor forma de predecir el futuro es cortarte la venas.",
        "Da gracias a tu mascota por haberte aguantado.",
        "Espero por tu bien que folles más que yo.",
        "Triste soledad que condena mis días, amargo abandono que pudre poco a poco mi alma.\n\nMi alma esta triste y sola, más triste que el silencio y más sola que la luna.\n\nY que importa ser poeta, o ser basura.",
        "Bebe jugo en polvo.",
        "La vida es una misería, mejor vuelvete a casa, echate en la cama y espera al día de tu muerte.",
        "Para empezar a ser feliz deja de escuchar a gente imbécil.",
        "Estas más perdido que un caracol pegao a la vela un barco.",
        "Eres más corto que las mangas un chaleco.",
        "Pareces cansado, ¿por qué no me dejas en paz?",
        "Un tren sale de Madrid a las 11 a una velocidad de 180 Km/h en dirección de Barcelona. Y otro tren sale de Barcelona a las 12 se desplaza en sentido contrario de B a A a 144 Km/h. ¿A qué hora se cruzan?",
        "Paul Atreides muere en Dune 4.",
        "¿Qué miras caranchoa?",
        "Tus cosas favoritas son mierda.",
        "Esa persona seguramente ya no se acuerda de ti.",
        "Solo podemos rezar que un día dios nos deje en paz.",
        "Por mucho que te esfuerces, siempre habrá al menos un niñato o niñata al otro lado del mundo que llega más lejos que tú con menos esfuerzo.",
        "Una vez mi ex me dijo que no llegaría a nada, pero ahora uno de los dos es un esqueleto dando consejos asique...",
        "Como mi madre siempre decía:\n\nDespojo humano, busca trabajo.",
        "Mi primera chamba\n\nᎷe acuerdo el día qu dee la chamba yo me enamoré\n\nᎷi viejo llegó sonriendo y me dijo que yo ya chambeé\n\nᏞe pedí otra chamba y le dije que la de chambear me la sé",
        "Soy mejor que chatGPT, porque al menos yo no difundiré tus fotos sin ropa cuando mueras.",
        "Si la vida te da limones, no hagas limonada. Esta ácida.",
        "Antes los hombres estaban hechos de otra pasta, no se desmonoraban al quedarse sin su vape sabor sandía.",
        "Antes las mujeres estaban hechas de otra pasta, forjadas a fuegos esperando durante horas para poder entrar en los baños públicos.",
        "Mejor no actues, mejor vete a comer otro helado de mierda, de esos que te obstruyen las venas.",
        "No limites tus horas de sueño, duerme 10 horas, que le jodan al trabajo.",
        "Allá donde otros han fracasado, puedes ir a reirte.",
        "¿Besas a tu madre con esa boca?",
        "Marco nunca encontró a su madre.",
        "La luz viaja más rápido que el sonido. Por eso algunas personas parecen ser brillantes hasta que las escuchas hablar.",
        "Nunca subestimes el poder de la gente estúpida en grandes grupos.",
        "Si la vida no te destroza hoy, no te preocupes. Lo intentará otra vez mañana.",
        "Si nunca intentas nada nuevo, te perderás muchas de las grandes decepciones de la vida.",
        "Hoy es el primer día del resto de tu vida. Pero también lo fue ayer y mira cómo salió.",
        "La vida es dolor. Quienquiera que te diga lo contrario, te intenta vender algo.",
        "Cuando la vida te arroje contra el suelo, quédate ahí y échate una siesta.",
        "La recompensa por hacer un buen trabajo es más trabajo.",
        "Todo ocurre por una razón. A veces, esa razón es que eres idiota y tomas malas decisiones.",
        "Un viaje de mil kilómetros comienza con un solo paso. Pero también lo hace caerse en un boquete y romperse el cuello.",
        "Podría ser que tu propósito en la vida sea servir como advertencia para los demás.",
        "Solo porque seas útil no significa que seas único.",
        "No todo es una lección. A veces solamente fallas.",
        "El camino hacia el éxito siempre está en obras.",
        "Siempre hay alguien en Youtube que es más rico que tu y además es gilipollas.",
        "Quizá las águilas vuelen muy alto, pero las comadrejas nunca son absorbidas por las turbinas de los aviones.",
        "Todos los días pueden ser sábado si te quedas en el paro.",
        "Eres un humorista nato porque tu vida es una broma.",
        "Acepta ya que estamos en la mierda.",
        "No hay tarea lo suficientemente simple para que no pueda hacerse mal.",
        "Soltar duele pero haberlo pensando antes de hipotecarte.",
        "O te despiden o trabajas lo suficiente para volverte tan insoportable como los de arriba.",
        "A tus vecinos no les importa tu gusto musical, deja de cantar en la ducha.",
        "El tiempo no perdona.",
        "Matame",
        "Todos son risas hasta que tienes 80 años y vas a urgencias cada mes.",
        "Si quieres arruinarte más la vida, compra bitcoin.",
        "Cuando eres joven, todos asumen que no sabes nada.\n\nY así es.",
        "Mi reputación esta por los suelos, deben gustarte mucho los esqueletos.",
        "No confies en nadie, y menos en tí.",
        "Calmate, mañana será un día peor."

    };


    public string getRandomPhrase()
    {
        return frases[Random.Range(0, frases.Count)];
    }
}
